### ISSUE TITLE
Gerando e Dockerizando o Projeto

### ISSUE THREAD

**Issue by Ueverton-oliveira** [Ueverton-oliveira/my-study-plan#100]
Links importantes:

- Instalar o Docker: https://docs.docker.com/engine/install
- Instalar o Docker Compose: https://docs.docker.com/compose/install
- Dominando o Docker: https://onebitcode.com/dominando-o-docker

1- Vamos criar nosso projeto, dentro da pasta desejada, rode no terminal os comandos a baixo:

`docker run --rm --user "$(id -u):$(id -g)" -v $(pwd):/usr/src -w /usr/src -ti ruby:3.2.2 bash`

`gem install rails -v 7.1.2`

`rails new onebit_exchange --database=postgresql --skip-bundle`

`exit`

`cd onebit_exchange`

2- Agora vamos configurar o docker, na raiz do projeto crie um arquivo chamado Dockerfile e insira o conteúdo:
```
FROM ruby:3.2.2

# add nodejs and yarn dependencies for the frontend
RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Instala nossas dependencias
RUN apt-get update && apt-get install -qq -y --no-install-recommends \
nodejs yarn build-essential libpq-dev imagemagick git-all nano

# Instalar bundler
RUN gem install bundler

# Seta nosso path
ENV INSTALL_PATH /onebitexchange

# Cria nosso diretório
RUN mkdir -p $INSTALL_PATH

# Seta o nosso path como o diretório principal
WORKDIR $INSTALL_PATH

# Copia o nosso Gemfile para dentro do container
COPY Gemfile ./

# Seta o path para as Gems
ENV BUNDLE_PATH /gems

# Copia nosso código para dentro do container
COPY . .

```

3- Agora crie também na raiz do projeto o arquivo docker-compose.yml e insira nele:

```
version: "3.8"

services:
db:
  image: "postgres:12.2"
  environment:
    - POSTGRES_PASSWORD=postgres
  volumes:
    - postgres:/var/lib/postgresql/data

app:
  build: .
  command: bash start.sh
  ports:
    - "3000:3000"
  environment:
    - DB_PASSWORD=postgres
  volumes:
    - .:/onebitexchange
    - gems:/gems
  depends_on:
    - db

volumes:
  postgres:
  gems:

```
4- Crie agora um arquivo chamado start.sh

# Instala as Gems
`bundle check || bundle install`

# Roda nosso servidor
`bundle exec puma -C config/puma.rb`

5- Para construir a imagem do ambiente rode:

`docker-compose build`
Obs: Caso seus comandos docker só funcionem usando o sudo antes, rode no console os seguintes comando para concertar:

`sudo groupadd docker`
`sudo usermod -aG docker $USER`
`sudo service docker restart`
